$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    autoplayTimeout:2000,
    nav:true,
    pullDrag:true,
    autoplay:true,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:false
        },
        600:{
            items:3,
            nav:false
        },
        1000:{
            items:5,
            nav:true,
            loop:true
        }
    }
})

